# Generated by Django 3.1.6 on 2021-02-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carhubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='instagram',
            new_name='phone_no',
        ),
    ]
