# Generated by Django 3.1.6 on 2021-02-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhubapp', '0002_auto_20210203_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
